### ISSUE TITLE
Support for parallelism?

### ISSUE THREAD

**Issue by privefl** [gabraham/flashpca#32]
A reviewer said that FlashPCA/FlashPCA2 support parallelism (I stated that FlashPCA2 doesn't).
Yet, I can't see anywhere in the `README` or in the documentation of `flashpcaR::flashpca` that it does.

Can you confirm that it does (not)?

**Comment by gabraham** [comment]
@privefl v1 of FlashPCA supported parallelism; v2 does not support parallelism since there is no obvious way to meaningfully perform IRAM in a parallel fashion from my experiments (i.e., better to use a large chunk of memory for doing non-parallel IRAM than to do 10x smaller IRAM using 1/10 the memory each and then somehow combine results).
