### ISSUE TITLE
flashpcaR should return center and scale like prcomp

### ISSUE THREAD

**Issue by gabraham** [gabraham/flashpca#6]

**Comment by gabraham** [comment]
flashpcaR will center and scale like prcomp if using <code>stand="sd"</code>

**Comment by JJohnsonAgR** [comment]
Gad,

Glad to hear it! I'll try it out when I get a chance!

Best regards,

James

James M. Johnson, PhD
Biostatistics and Marker Applications Manager
AgReliant Genetics LLC<http://www.agreliantgenetics.com/>
4640 East State Road 32<x-apple-data-detectors://0/1>
Lebanon, Indiana 46052<x-apple-data-detectors://1/0>
James.Johnson@AgReliantGenetics.com<mailto:James.Johnson@AgReliantGenetics.com%0d>
Phone: +1 (765) 482-9833 (Ext. 302)<tel:+1%20(765)%20482-9833;302>

On Nov 29, 2015, at 11:36 PM, Gad Abraham <notifications@github.com<mailto:notifications@github.com>> wrote:


flashpcaR will center and scale like prcomp if using stand="sd"

—
Reply to this email directly or view it on GitHub<https://github.com/gabraham/flashpca/issues/6#issuecomment-160513912>.

________________________________
This email and any files transmitted with it may be confidential and are intended solely for the use of the individual(s) or entity to whom they are addressed. If you have received this email in error please promptly notify the sender. If you are not the named addressee you should not disseminate, distribute or otherwise copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

**Comment by gabraham** [comment]
@JJohnsonAgR sorry,

**Comment by JJohnsonAgR** [comment]
No rush. It would be great but I'm using prcomp in the meantime.

**Comment by gabraham** [comment]
@JJohnsonAgR I've added this ability to flashpcaR in the master branch, e.g.,:
<pre>
> f <- flashpca(X, ndim=10, stand="sd")
> names(f)
[1] "values"     "vectors"    "projection" "center"     "scale"
> summary(f$center)
     Min.   1st Qu.    Median      Mean   3rd Qu.      Max.
-0.200500 -0.049170 -0.002258 -0.002408  0.042770  0.225200
> summary(f$scale)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
 0.8399  0.9636  0.9973  0.9980  1.0330  1.1640
</pre>

 Are you able to install flashpcaR from source and check that it works?

**Comment by gabraham** [comment]
@JJohnsonAgR closing this issue; please re-open if necessary.

**Comment by JJohnsonAgR** [comment]
@gabraham my apologies. I didn't see you made this update in December. I'll take a look soon. I appreciate you taking the time to do this.
